[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:llama-server]
command=llama-server -hf mistralai/Ministral-3-3B-Instruct-2512-GGUF --host 0.0.0.0 --port 8080
environment=HF_HOME="/tmp/huggingface"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true

[program:django-web]
command=gunicorn main.wsgi:application --bind 0.0.0.0:8000 --timeout 300 --workers 3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
